# Generated by Django 4.2.3 on 2023-07-22 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytical_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateField()),
            ],
            options={
                'db_table': 'scv_analytical_plan',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=80)),
                ('assignment_status', models.CharField(max_length=20)),
                ('deadline', models.DateTimeField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'scv_assignment',
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'scv_career',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'scv_level',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'scv_role',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'scv_subjects',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('names', models.CharField(max_length=40)),
                ('surnames', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('created_by', models.IntegerField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemAnalyticalPlans.role')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemAnalyticalPlans.subject')),
            ],
            options={
                'db_table': 'scv_user',
            },
        ),
        migrations.CreateModel(
            name='Subject_career_level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemAnalyticalPlans.career')),
                ('id_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemAnalyticalPlans.level')),
                ('id_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemAnalyticalPlans.subject')),
            ],
            options={
                'db_table': 'scv_subject_career_level',
            },
        ),
        migrations.CreateModel(
            name='Plan_version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=80)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.JSONField()),
                ('is_actual', models.BooleanField(default=False)),
                ('id_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemAnalyticalPlans.analytical_plan')),
            ],
            options={
                'db_table': 'scv_plan_version',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('id_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemAnalyticalPlans.assignment')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemAnalyticalPlans.user')),
            ],
            options={
                'db_table': 'scv_comment',
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='id_assigner_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigner', to='systemAnalyticalPlans.user'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='id_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemAnalyticalPlans.analytical_plan'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='systemAnalyticalPlans.user'),
        ),
        migrations.AddField(
            model_name='analytical_plan',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemAnalyticalPlans.user'),
        ),
        migrations.AddConstraint(
            model_name='subject_career_level',
            constraint=models.UniqueConstraint(fields=('id_career', 'id_level', 'id_subject'), name='pk_compuesta'),
        ),
    ]
