# Generated by Django 4.2.3 on 2023-07-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemAnalyticalPlans', '0002_alter_user_password_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_version',
            name='creation_date',
            field=models.DateTimeField(),
        ),
    ]
