# Generated by Django 4.2.3 on 2023-07-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemAnalyticalPlans', '0003_alter_plan_version_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytical_plan',
            name='creation_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='analytical_plan',
            name='update_date',
            field=models.CharField(max_length=10),
        ),
    ]
